---
-
  hosts: webservers
  become: True
  tasks:
    - name: Installing httpdservice
      yum:
        name: httpd
        state: present
    - name: Starting and enabling httpdservice
      service:
        name: httpd
        state: started
        enabled: yes


-
  hosts: prod
  become: True
  tasks:
    - name: Installing mariadbservice
      yum:
        name: 
          - mariadb-server
          - mariadb-common
        state: present
    - name: Starting and enabling mariadbservice
      service:
        name: mariadb
        state: started
        enabled: yes
...


